version: "1"
services:

  oj-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5437:5432"

  oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.0
    restart: always
    read_only: true
    pull_policy: never
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS # secret.key
      # - judger_debug=1

  backend:
    image: juniper0917/csep-be:0.1
    restart: always
    pull_policy: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
      - ./data/backend/certbot/conf/fullchain.pem:/etc/letsencrypt/live/csep.co.kr/fullchain.pem
      - ./data/backend/certbot/conf/privkey.pem:/etc/letsencrypt/live/csep.co.kr/privkey.pem
      - ./data/backend/certbot/www:/var/www/certbot
    env_file:
      - .env
    environment:
      - JUDGE_SERVER_TOKEN=CHANGE_THIS # secret.key
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
      image: certbot/certbot
      restart: unless-stopped
      volumes:
        - ./data/backend/certbot/conf:/etc/letsencrypt
        - ./data/backend/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"