version: "1"
services:

  oj-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5437:5432"

  oj-judge:
    image: juniper0917/csep-js:0.1
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS # secret.key
      # - judger_debug=1

  backend:
    image: juniper0917/csep-be:0.1
    restart: always
    pull_policy: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
      - ./data/backend/certbot/www:/var/www/certbot
      - /etc/letsencrypt/live/csep.pusan.ac.kr/fullchain.pem:/etc/letsencrypt/live/csep.pusan.ac.kr/fullchain.pem
      - /etc/letsencrypt/live/csep.pusan.ac.kr/privkey.pem:/etc/letsencrypt/live/csep.pusan.ac.kr/privkey.pem
    env_file:
      - .env
    environment:
      - JUDGE_SERVER_TOKEN=CHANGE_THIS # secret.key
      - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"

  scheduler:
    image: juniper0917/csep-scheduler:latest
    restart: always
    depends_on:
      - oj-postgres
      - backend
    volumes:
      - ../scheduler/logs:/app/logs
    env_file:
      - .env

