services:
  oj-judge:
    image: juniper0917/csep-js:0.1
    restart: always
#    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ../../data/backend/test_case:/test_case:ro
      - ../../data/judge_server/log:/log
      - ../../data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://backend:8080/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS # secret.key
      # - judger_debug=1
    networks:
      - prod-network

networks:
  prod-network:
    external: true
    name: code-place-prod-network