name: Change detection and Image tagging with github sha (DEV)

on:
  push:
    paths-ignore:
      - 'deployment/**'
      - 'scripts/**'
    branches: [ develop ]
  pull_request:
    paths-ignore:
      - 'deployment/**'
      - 'scripts/**'
    branches: [ develop ]
  workflow_dispatch:

jobs:
  detect-changes-by-component:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      scheduler: ${{ steps.filter.outputs.scheduler }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            scheduler:
              - 'scheduler/**'
            frontend:
              - 'frontend/**'

  ci-backend-dev:
    needs: [detect-changes-by-component]
    if: ${{ needs.detect-changes-by-component.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/code-place-dev/backend:${{ github.sha }}-dev
            ${{ secrets.HARBOR_REGISTRY }}/code-place-dev/backend:latest

  ci-scheduler-dev:
    needs: [versioning, detect-changes-by-component]
    if: ${{ needs.detect-changes-by-component.outputs.scheduler == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler
          file: ./scheduler/Dockerfile
          push: true
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/code-place-dev/scheduler:${{ github.sha }}-dev
            ${{ secrets.HARBOR_REGISTRY }}/code-place-dev/scheduler:latest
