name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build_test:
    strategy:
      matrix:
        node-version: [ '14.x', '16.x', '18.x' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
                - name: Use Node.js
                uses: actions/setup-node@v4
                with:
                  node-version: '20.x'
